export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
  team
}: {
  children: React.ReactNode,
  team: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>(root layout){children}{team}</body>
    </html>
  )
}
